// Private local Node API. Uses Node built-ins only; deploy behind HTTPS for remote use.
const http=require('node:http');
const fs=require('node:fs/promises');
const path=require('node:path');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const HOST='127.0.0.1', PORT=Number(process.env.PT_API_PORT||process.env.PORT||4173);
const DATA_DIR=path.resolve(process.env.PT_DATA_DIR||path.join(__dirname,'.data'));
require('node:fs').mkdirSync(DATA_DIR,{recursive:true});
const MAX_BODY=2*1024*1024, SESSION_DAYS=30, SHARE_DAYS=7;
const KEYS=['pt_user','pt_cycles','pt_diet','pt_exercise','pt_settings','pt_trash','pt_symptoms','pt_medication','pt_shares','pt_analytics_cache','pt_feedback'];
const ARRAY_KEYS=new Set(['pt_cycles','pt_diet','pt_exercise','pt_trash','pt_symptoms','pt_medication','pt_feedback']);
const db=new DatabaseSync(path.join(DATA_DIR,'tracker.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,salt TEXT NOT NULL,password_hash TEXT NOT NULL,profile TEXT NOT NULL,created_at TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS records(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,data TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS shares(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,snapshot TEXT NOT NULL,expires_at INTEGER NOT NULL,revoked INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS reminders(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,enabled INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY, user_id TEXT, event TEXT NOT NULL, at INTEGER NOT NULL);`);
const stmt={user:db.prepare('SELECT * FROM users WHERE email=?'),byId:db.prepare('SELECT * FROM users WHERE id=?'),createUser:db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)'),upProfile:db.prepare('UPDATE users SET profile=?,updated_at=? WHERE id=?'),record:db.prepare('SELECT * FROM records WHERE user_id=?'),upRecord:db.prepare('INSERT INTO records VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at'),session:db.prepare('SELECT user_id,expires_at FROM sessions WHERE token_hash=?'),addSession:db.prepare('INSERT INTO sessions VALUES(?,?,?)'),delSession:db.prepare('DELETE FROM sessions WHERE token_hash=?'),addShare:db.prepare('INSERT INTO shares VALUES(?,?,?,?,0)'),getShare:db.prepare('SELECT snapshot,expires_at,revoked FROM shares WHERE id=?'),revokeShare:db.prepare('UPDATE shares SET revoked=1 WHERE id=? AND user_id=?'),audit:db.prepare('INSERT INTO audit(user_id,event,at) VALUES(?,?,?)')};
function json(res,status,value,extra={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extra});res.end(JSON.stringify(value));}
function local(req){const host=req.headers.host||'';if(!/^(localhost|127\.0\.0\.1)(:\d+)?$/i.test(host))return false;const origin=req.headers.origin;if(!origin)return true;try{const u=new URL(origin);return ['localhost','127.0.0.1'].includes(u.hostname);}catch{return false;}}
function body(req){return new Promise((resolve,reject)=>{let size=0,chunks=[];req.on('data',c=>{size+=c.length;if(size>MAX_BODY){reject(Object.assign(Error('Body too large'),{status:413}));req.destroy();return;}chunks.push(c);});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString()||'{}'));}catch{reject(Object.assign(Error('Invalid JSON'),{status:400}));}});req.on('error',reject);});}
function safeData(input,profile){if(!input||typeof input!=='object'||Array.isArray(input))return null;const data={};for(const key of KEYS){const v=input[key];if(v===undefined){data[key]=ARRAY_KEYS.has(key)?[]:key==='pt_settings'?{}:null;continue;}if(ARRAY_KEYS.has(key)?!Array.isArray(v):v!==null&&(typeof v!=='object'||Array.isArray(v)))return null;data[key]=v;}data.pt_user=profile;data.pt_shares={};return data;}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex');}
function cookie(req){const raw=req.headers.cookie||'';return raw.split(';').map(s=>s.trim()).find(s=>s.startsWith('pt_session='))?.slice(11)||'';}
function publicUser(profile){return profile||{};}
function sharedUser(profile){const {email,localAuth,gynaeContact,...safe}=profile||{};return safe;}
function sessionUser(req){const token=cookie(req);if(!token)return null;const key=hash(token),row=stmt.session.get(key);if(!row)return null;if(row.expires_at<Date.now()){stmt.delSession.run(key);return null;}return {token,key,user:stmt.byId.get(row.user_id)};}
function startSession(userId){const token=crypto.randomBytes(32).toString('base64url'),expires=Date.now()+SESSION_DAYS*864e5;stmt.addSession.run(hash(token),userId,expires);return {token,expires};}
function sessionCookie(token,maxAge=SESSION_DAYS*86400){return `pt_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}`;}
function profileFor(user){return JSON.parse(user.profile);}
function getData(user){const row=stmt.record.get(user.id);return row?JSON.parse(row.data):safeData({},profileFor(user));}
function putData(user,input){const data=safeData(input,profileFor(user));if(!data)return null;const now=Date.now();stmt.upRecord.run(user.id,JSON.stringify(data),now);stmt.upProfile.run(JSON.stringify(data.pt_user),now,user.id);return {data,updatedAt:now};}
function log(user,event){stmt.audit.run(user?.id||null,event,Date.now());}
const failures=new Map();
function limited(req){const key=`${req.socket.remoteAddress}:${Math.floor(Date.now()/900000)}`,n=failures.get(key)||0;return n>=8;}
function fail(req){const key=`${req.socket.remoteAddress}:${Math.floor(Date.now()/900000)}`;failures.set(key,(failures.get(key)||0)+1);}
function seedData(profile,input){const data=safeData(input,profile)||safeData({},profile);data.pt_user=profile;return data;}
async function api(req,res,url){const p=url.pathname;
 if(p==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,storage:'sqlite',authenticated:Boolean(sessionUser(req))});
 if(p==='/api/auth/register'&&req.method==='POST'){if(limited(req))return json(res,429,{error:'Too many attempts. Try again later.'});const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<10)return json(res,400,{error:'Enter a valid email and a passphrase of at least 10 characters.'});const existing=stmt.user.get(email);if(existing){const matches=crypto.scryptSync(password,existing.salt,64).equals(Buffer.from(existing.password_hash,'hex'));if(matches){const session=startSession(existing.id),profile=profileFor(existing);log(existing,'login');return json(res,200,{user:publicUser(profile),data:getData(existing),updatedAt:existing.updated_at},{'set-cookie':sessionCookie(session.token)});}fail(req);return json(res,409,{error:'An account with this email already exists. Sign in with its passphrase.'});}const profile={...(b.profile||{}),email};delete profile.localAuth;const uid=crypto.randomUUID(),salt=crypto.randomBytes(16).toString('hex'),pw=crypto.scryptSync(password,salt,64).toString('hex'),now=Date.now();const data=seedData(profile,b.data);db.exec('BEGIN');try{stmt.createUser.run(uid,email,salt,pw,JSON.stringify(profile),new Date(now).toISOString(),now);stmt.upRecord.run(uid,JSON.stringify(data),now);log({id:uid},'account_created');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}const s=startSession(uid);return json(res,201,{user:publicUser(profile),data,updatedAt:now},{'set-cookie':sessionCookie(s.token)});}
 if(p==='/api/auth/login'&&req.method==='POST'){if(limited(req))return json(res,429,{error:'Too many attempts. Try again later.'});const b=await body(req),email=String(b.email||'').trim().toLowerCase(),user=stmt.user.get(email),valid=user&&crypto.scryptSync(String(b.password||''),user.salt,64).equals(Buffer.from(user.password_hash,'hex'));if(!valid){fail(req);return json(res,401,{error:'Email or passphrase is incorrect.'});}const s=startSession(user.id);log(user,'login');const profile=profileFor(user);return json(res,200,{user:publicUser(profile),data:getData(user),updatedAt:user.updated_at},{'set-cookie':sessionCookie(s.token)});}
 if(p==='/api/auth/session'&&req.method==='GET'){const auth=sessionUser(req);if(!auth)return json(res,401,{error:'Sign in required.'});const data=getData(auth.user);return json(res,200,{user:publicUser(profileFor(auth.user)),data,updatedAt:stmt.record.get(auth.user.id)?.updated_at||0});}
 if(p==='/api/auth/logout'&&req.method==='POST'){const auth=sessionUser(req);if(auth){log(auth.user,'logout');stmt.delSession.run(auth.key);}return json(res,200,{ok:true},{'set-cookie':sessionCookie('',0)});}
 const auth=sessionUser(req);
 if(p.startsWith('/api/shares/')&&req.method==='GET'){const id=decodeURIComponent(p.slice('/api/shares/'.length)),share=stmt.getShare.get(id);if(!share||share.revoked||share.expires_at<Date.now())return json(res,404,{error:'Snapshot not found or expired.'});return json(res,200,{snapshot:JSON.parse(share.snapshot),expiresAt:new Date(share.expires_at).toISOString()});}
 if(!auth)return json(res,401,{error:'Sign in required.'});const user=auth.user;
 if(p==='/api/data'&&req.method==='GET'){const row=stmt.record.get(user.id);return json(res,200,{data:getData(user),updatedAt:row?.updated_at||0});}
 if(p==='/api/data'&&req.method==='PUT'){const b=await body(req),result=putData(user,b.data);if(!result)return json(res,400,{error:'Invalid tracker data.'});return json(res,200,{ok:true,updatedAt:result.updatedAt});}
 if(p==='/api/data'&&req.method==='DELETE'){const profile=profileFor(user),data=safeData({},profile);putData(user,data);db.prepare('DELETE FROM shares WHERE user_id=?').run(user.id);log(user,'data_deleted');return json(res,200,{ok:true,data});}
 if(p==='/api/export'&&req.method==='GET'){const d=getData(user),{localAuth,email,...profile}=d.pt_user||{};log(user,'export');return json(res,200,{user:profile,cycles:d.pt_cycles,diet:d.pt_diet,exercise:d.pt_exercise,symptoms:d.pt_symptoms,medication:d.pt_medication});}
 if(p==='/api/account'&&req.method==='DELETE'){const b=await body(req);if(!crypto.scryptSync(String(b.password||''),user.salt,64).equals(Buffer.from(user.password_hash,'hex')))return json(res,401,{error:'Passphrase is incorrect.'});log(user,'account_deleted');db.prepare('DELETE FROM users WHERE id=?').run(user.id);return json(res,200,{ok:true},{'set-cookie':sessionCookie('',0)});}
 if(p==='/api/shares'&&req.method==='POST'){const d=getData(user),id=crypto.randomBytes(24).toString('base64url'),expires=Date.now()+SHARE_DAYS*864e5,snapshot={user:sharedUser(d.pt_user),cycles:d.pt_cycles,symptoms:d.pt_symptoms.slice(0,8)};stmt.addShare.run(id,user.id,JSON.stringify(snapshot),expires);log(user,'share_created');return json(res,201,{id,expiresAt:new Date(expires).toISOString()});}
 if(p.startsWith('/api/shares/')&&req.method==='DELETE'){const id=decodeURIComponent(p.slice('/api/shares/'.length));stmt.revokeShare.run(id,user.id);log(user,'share_revoked');return json(res,200,{ok:true});}
 if(p==='/api/reminders'&&req.method==='GET'){const row=db.prepare('SELECT enabled FROM reminders WHERE user_id=?').get(user.id);return json(res,200,{enabled:Boolean(row?.enabled)});}
 if(p==='/api/reminders'&&req.method==='PUT'){const b=await body(req);db.prepare('INSERT INTO reminders VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET enabled=excluded.enabled,updated_at=excluded.updated_at').run(user.id,b.enabled?1:0,Date.now());return json(res,200,{enabled:Boolean(b.enabled)});}
 return json(res,404,{error:'Not found.'});
}
async function handle(req,res){if(!local(req))return json(res,403,{error:'Local requests only.'});const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return api(req,res,url);if(req.method!=='GET')return json(res,405,{error:'Method not allowed.'});const root=path.join(__dirname,'dist'),relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)),file=path.resolve(root,relative);if(!file.startsWith(root+path.sep))return json(res,404,{error:'Not found.'});try{const bytes=await fs.readFile(file),ext=path.extname(file),type=ext==='.html'?'text/html; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':ext==='.svg'?'image/svg+xml':'application/octet-stream';res.writeHead(200,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(bytes);}catch{json(res,404,{error:'File not found.'});}}
http.createServer((req,res)=>handle(req,res).catch(e=>{console.error(`[api] ${req.method} ${new URL(req.url,'http://localhost').pathname}: ${e.message}`);if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Local server error.'});else res.destroy();})).listen(PORT,HOST,()=>console.log(`Cycle Notes API: http://${HOST}:${PORT} · SQLite: ${path.join(DATA_DIR,'tracker.sqlite')}`));

